# INFO:
# > ssh-to-age < ~/.ssh/id_ed25519.pub
# or
# > nix run nixpkgs#ssh-to-age -- < ~/.ssh/id_ed25519.pub
#
# TIPS:
# you can change this file location
# > sops --config .sops.yaml <secrets-file.yaml>
#
# to rekey secrets
# > sops updatekeys ./file

keys:
  - &pcRyazenka age16dzy76gf6jcw03cppgghm7a8ld4g57f73z85wcj9fvq7w3ct53rs4rclm7
  - &thinkpadT14 age16ermygpuxg2k6mmyu3q9nzjptzjdqz6kyswnhpxktqa58stff5cs3aupl6

creation_rules:
  - path_regex: .+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *pcRyazenka
          - *thinkpadT14
