jobs:
  update-flake:
    name: Run build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install Cachix
        uses: cachix/cachix-action@v17
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: xache
      - env:
          FILE: github-actions-inputs
          PREFIXES_DATA: ${{ inputs.prefixes }}
        name: Add additional prefix ignores
        run: |
          echo $PREFIXES_IGNORES > $FILE
          git add $FILE
      - name: Build cachix-farmer
        run: |
          nix build .#__cachix-farmed --no-link --print-out-paths
name: Upload prebuilt Nix binaries to Cachix
"on":
  workflow_dispatch:
    inputs:
      prefixes:
        required: true
